# FMS Orchestr8 Gateway Configuration
# This ConfigMap configures the guardrails gateway with detectors and routing rules
apiVersion: v1
kind: ConfigMap
metadata:
  name: fms-orchestr8-config-gateway
  labels:
    app: fmstack-nlp
data:
  config.yaml: |
    orchestrator:
      host: "localhost"
      port: 8032
    detectors:
      - name: regex_language
        input: true
        output: true
        detector_params:
          regex:    
            - \b(?i:orange|apple|cranberry|pineapple|grape)\b
      - name: hap
        input: true
        output: true
        detector_params: {}
      - name: prompt_injection
        input: true
        output: true
        detector_params: {}
      - name: gibberish_text_detector
        input: true
        output: true
        detector_params: {}
    routes:
      - name: all
        detectors:
          - regex_language
          - hap
          - prompt_injection
          - gibberish_text_detector
      - name: hap
        detectors:
          - hap
        fallback_message: "I'm sorry, I cannot help with that."
      - name: passthrough
        detectors:
      - name: prompt_injection
        detectors:
      - name: gibberish_text_detector
        detectors: